version: "3.9"
services:
    soketi:
        container_name: "soketi_server"
        restart: unless-stopped
        image: "soketi"
        build:
            dockerfile: ./Dockerfile-soketi
        ports:
            - "${SOKETI_PORT:-6001}:6001"
            - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
        networks:
            - soketi
        volumes:
            - "./soketi:/app/soketi"

    db:
        image: postgres
        restart: always
        environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: root

networks:
    soketi:
        driver: bridge
